#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# tell Tmux were using screen-256color
export TERM="screen-256color"

# set mysql prompt to display user@host tbl[table]
export MYSQL_PS1="\u@\h tbl[\d]> "


# SwiftOtter config converted from bash by Catalina
export SWIFTOTTER_VAGRANT_ENV=/Volumes/Development/vagrant
export SWIFTOTTER_PROJECTS=/Volumes/Development/swiftotter

ssh-add -K ~/.ssh/id_rsa

export PATH=$PATH:$HOME/.composer/vendor/bin:
export SWIFTOTTER_VAGRANT_ENV=/Volumes/Development/vagrant

# PHP Versions
#export PATH="/usr/local/opt/php@7.2/bin:$PATH"
#export PATH="/usr/local/opt/php@7.2/sbin:$PATH"

export PATH="/usr/local/opt/php@7.3/bin:$PATH"
export PATH="/usr/local/opt/php@7.3/sbin:$PATH"

#export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

